#%RAML 1.0 DataType
type: object
description: Merchant Account Merchant Contact info
properties:
  appEmail:
    description: Merchant email
    type: string
    required: false
  extension:
    type: string
    required: false
  title:
    type: string
    required: false
  phone:
    type: integer
    format: int32
    required: false
  firstName:
    type: string
    required: false
  lastName:
    type: string
    required: false