#%RAML 1.0 DataType
type: object
description: Merchant Account Biz Info Biz Checking
properties:
  bankName:
    maxLength: 30
    type: string
  checkingAccountNumber:
    maxLength: 17
    type: string
    required: false
  transitRoutingNumber:
    type: string
    required: false
  yearsOpen:
    maximum: 999
    type: integer
    format: int32
    required: false
  bankAccType:
    type: integer
    required: false
  merchBankAcctSrnum:
    type: integer
    required: false