#%RAML 1.0 DataType
type: object
description: Merchant Account Pricing Fields Recurring Charge Fees
properties:
  amount:
    maximum: 9999999.99
    type: number
    format: double
  description:
    maxLength: 40
    type: string
  chargeRecType:
    maximum: 999999
    type: integer
    format: int32
  chargeRecNum:
    maximum: 999999
    type: integer
    format: int32