#%RAML 1.0 AnnotationTypeDeclaration
type: object
allowedTargets: API
description: Annotation RAML info
properties:
  contact?:
    properties:
      name?: string
      url?: string
      email?: string
  license?:
    properties:
      name?: string
      url?: string
